name: Holiday Alert

on:
  # Allow manual runs from the Actions tab
  workflow_dispatch:

  # Also run automatically every day at 09:00 Europe/London
  schedule:
    # 08:00 UTC = 09:00 BST/Europe-London
    - cron: '0 8 * * *'

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

   - name: Run holiday bot
     env:
       BOT_TOKEN:       ${{ secrets.BOT_TOKEN }}
       CHANNEL_ID:      ${{ secrets.CHANNEL_ID }}
       GROUP_CHAT_ID:   ${{ secrets.GROUP_CHAT_ID }}
     run: python holidays_bot.py
